### ISSUE TITLE
todo: '22.04.01~'22.06.30 web-react study todo list

### ISSUE THREAD

**Issue by dev-heeseok** [dev-heeseok/web-react#1]
- [x] 생활코딩 web1 html
- [x] 생활코딩 web2 css
- [x] 생활코딩 web2 java script
- [x] 생활코딩 java script object-oriented programming
- [x] 생활코딩 web2 node.js
- [x] 생활코딩 React
- [x] 생활코딩 React 2022 개정판
- [x] 생활코딩 React class vs function style
- [x] 생활코딩 JavaScript Immutability
- [x] velopert React.js 강좌 시리즈
- [x] 생활코딩 Express
- [x] 생활코딩 Redux
- [x] 생활코딩 React Redux

**Comment by dev-heeseok** [comment]
생활코딩 스터디는 잘되고 있나요??

**Comment by kimkmin357** [comment]
테스트 코멘트

**Comment by dev-heeseok** [comment]
@kimkmin357 스터디 항목 공유합니다

https://youtube.com/playlist?list=PLuHgQVnccGMDZP7FJ_ZsUrdCGH68ppvPb

**Comment by dev-heeseok** [comment]
4/26 (화) 진행 사항 공유  
- 생활코딩을 WEB2 Node.js 스터디 완료

**Comment by DeukHan** [comment]
Readme 파일에 npm create-react-app으로 되어 있는데 저는 npx create-react-app으로 해야 진행되던데
수정될 필요가 있다면 확인 부탁드리겠습니다.
@dev-heeseok

**Comment by dev-heeseok** [comment]
npx 는 최신 package 를 사용하기 위해 패키지를 local 에 저장하지 않고 사용 시 실시간으로 다운 받아 사용하는 것입니다. 다르게 작동한다면 나중에 같이 이야기 해보아요 
@DeukHan

**Comment by kimkmin357** [comment]
create-react-app 이라는 것도 설치해서 사용하는 모듈인데,
npm을 사용할 경우 create-react-app을 나의 PC에 설치해서 사용하겠다는 의미이고
npx를 사용할 경우 create-react-app이라는 모듈을 임시로 설치(실행)해서 사용하고 휘발시켜버리겠다는 것임.

여기 참고
https://velog.io/@eunmi/create-react-app-%EC%84%A4%EC%B9%98
@DeukHan @dev-heeseok

**Comment by dev-heeseok** [comment]
@kimkmin357 @DeukHan 

어제 이야기했던 참고사이트 입니다
[Poiemaweb](https://poiemaweb.com)

**Comment by dev-heeseok** [comment]
# 5/8(일) 스터디 진햏사항 공유

- React 동영상 강의 수강 완료 (생활코딩 react, react 2022 개정판)
- web tutorial merge 진행 중 (react, nodejs)
- class vs function style, immutability, redux 개념 스터디 진행 중
- redux 스터디를 위한 web-javascript repository 추가

추가적으로 toy project 개발을 위해 bootstrap, sass, database 관련 스터디가 필요해 보임

**Comment by dev-heeseok** [comment]
# 5/18(수) 스터디 진행사항 공유

- Node.js Tutorial 을 Express 를 이용하여 코드 리펙토링 진행
- velopert React.js 강의 수강
- Redux 를 이용한 Tutorial 추가

스터디가 더 필요한 항목으로는 MongoDB 및 MERN(MongoDB, Express, React, Node) Stack 개발을 위한 환경설정 방법입니다.  
5월 22일 일요일까지 2가지 항목에 대한 스터디 완료를 목표로 하고 있습니다.

**Comment by dev-heeseok** [comment]
# 5/23(월) 스터디 진행사항 공유

- mongoDB, mongoose 를 이용하여 db 스카마 구성
- Node.js, Express 를 이용하여 Server 구축
- React, Bootstrap 을 이용하여 Client 개발
- Server-Client 연동을 통한 SignUp Tutorial 추가

**Comment by dev-heeseok** [comment]
# 6/1 (수) 스터디 진행사항 공유

## 진행 완료한 이슈

- Proxy 를 이용하여 Server-Client 간의 통신을 수행할 수 있도록 기능 구현 완료 #18 
- Build 된 Client App 을 Server 에 의해 Service 될 수 있도록 기능 구현 완료
- Heroku 를 이용한 Deploy 환경 셋팅 진행중

## 진행할 이슈

- Toy Project 기획 및 진행
- Signup 후 token 방식으로 login 유지할 수 있도록 스터디 진행
